# context version definition
VERSION := 6.10.0
RELEASE := 1

# log
VERBOSE         := 1
PACKER_LOG      := 0
PACKER_HEADLESS := true

SERVICES := service_jenkins \
        service_TNLCM \
        service_UERANSIM

.DEFAULT_GOAL := help

# default directories
DIR_ONEAPPS := ../one-apps
DIR_BUILD  := build
DIR_EXPORT := export
$(shell mkdir -p ${DIR_BUILD} ${DIR_EXPORT})

######## PLEASE MODFIY THESE 2 VARIABLES ########################
# Where the generated appliance will be moved
DIR_APPLIANCES := /var/lib/one/6gsandbox-marketplace/
# Where the metadata files are located
# WARNING: the building process will fail if the corresponding metadata yaml file does not exist or is incorrectly formated
DIR_METADATA := /opt/marketplace/appliances/all/
#################################################################


# don't delete exported
.SECONDARY: $(patsubst %, $(DIR_EXPORT)/%.qcow2, $(SERVICES))

# logging func
INFO=sh -c 'if [ $(VERBOSE) = 1 ]; then  echo [INFO] $$1; fi' INFO

# export all variables
export
