# context version definition
VERSION := 6.10.0
RELEASE := 1

# log
VERBOSE         := 1
PACKER_LOG      := 0
PACKER_HEADLESS := true

SERVICES := service_jenkins \
        service_TNLCM \
        service_routemanager \
        service_dns \
        service_bastion \
        service_UERANSIM \
        service_ntp_server \
        service_phoenix \
        service_openFgs \
        service_ELCM \
        service_Collector_INT \
        service_OCF

.DEFAULT_GOAL := help

# default directories
DIR_ONEAPPS := ../one-apps
DIR_BUILD  := build
DIR_EXPORT := export
$(shell mkdir -p ${DIR_BUILD} ${DIR_EXPORT})

######## PLEASE MODFIY THESE 2 VARIABLES ########################
# Where the generated appliance will be moved
DIR_APPLIANCES := /var/lib/one/6gsandbox-marketplace/
# Where the metadata files will be created/updated
DIR_METADATA := /opt/marketplace-community/marketplace/appliances/
# URL of the appliance repository
URL_APPLIANCES := https://rawimages.mobilesandbox.cloud:9443/
#################################################################


# don't delete exported
.SECONDARY: $(patsubst %, $(DIR_EXPORT)/%.qcow2, $(SERVICES))

# logging func
INFO=sh -c 'if [ $(VERBOSE) = 1 ]; then  echo [INFO] $$1; fi' INFO

# export all variables
export
